import type { Metadata } from "next";
import Script from "next/script";
import ClerkProviderWrapper from "@/components/ClerkProviderWrapper";
import Navbar from "@/components/Navbar";
import { ThemeProvider } from "@/components/ThemeProvider";
import "./globals.css";

export const metadata: Metadata = {
  title: "Familying",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
        <head>
          <Script id="theme-init" strategy="beforeInteractive">{`
            (function(){
              try {
                var stored = localStorage.getItem('theme');
                var preferDark = window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches;
                var isDark = stored === 'dark' || (!stored || stored === 'system') && preferDark;
                var root = document.documentElement;
                if (isDark) root.classList.add('dark'); else root.classList.remove('dark');
              } catch(_) {}
            })();
          `}</Script>
        </head>
        <body className="antialiased font-sans">
          <ThemeProvider>
            <ClerkProviderWrapper>
              <div className="container mx-auto">
                <Navbar />
                {children}
              </div>
            </ClerkProviderWrapper>
          </ThemeProvider>
        </body>
      </html>
  );
}
